# Generated by Django 5.2.4 on 2025-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos_clientes/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoLeido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MensajeCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('categoria', models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional'), ('tributaria', 'Tributaria (SII)'), ('bcentral', 'Banco Central'), ('achs', 'ACHS'), ('dtrabajo', 'Dirección del Trabajo'), ('politica', 'Política'), ('tecnologia', 'Tecnología'), ('economica', 'Económica'), ('negocios', 'Negocios'), ('empresas', 'Empresas'), ('mercados', 'Mercados'), ('otros', 'Otros'), ('laboral', 'Laboral')], max_length=50)),
                ('fuente', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fecha_scraping', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
