# Generated by Django 5.2.3 on 2025-06-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('url', models.URLField(unique=True)),
                ('categoria', models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional'), ('tributaria', 'Tributaria (SII)'), ('bcentral', 'Banco Central'), ('achs', 'ACHS'), ('dtrabajo', 'Dirección del Trabajo'), ('politica', 'Política'), ('tecnologia', 'Tecnología')], max_length=50)),
                ('fuente', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('fecha_scraping', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
