# Generated by Django 5.2.3 on 2025-06-26 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('nacional', 'Nacional'), ('internacional', 'Internacional'), ('tributaria', 'Tributaria (SII)'), ('bcentral', 'Banco Central'), ('achs', 'ACHS'), ('dtrabajo', 'Dirección del Trabajo'), ('politica', 'Política'), ('tecnologia', 'Tecnología'), ('economica', 'Económica'), ('negocios', 'Negocios'), ('empresas', 'Empresas'), ('mercados', 'Mercados'), ('otros', 'Otros')], max_length=50),
        ),
    ]
